### ISSUE TITLE
Broken dependeny reqirements?

### ISSUE THREAD

**Issue by TheWizier** [frankligy/SNAF#29]
Attempting to install the package using poetry yields this error:

Because snaf (0.7.0) @ git+https://github.com/frankligy/SNAF.git@e23ce39512a1a7f58c74e59b4b7cedc89248b908 depends on pandas (1.3.4) which depends on numpy (>=1.19.2), snaf (0.7.0) @ git+https://github.com/frankligy/SNAF.git@e23ce39512a1a7f58c74e59b4b7cedc89248b908 requires numpy (>=1.19.2).
So, because project depends on SNAF (0.7.0) @ git+https://github.com/frankligy/SNAF.git@e23ce39512a1a7f58c74e59b4b7cedc89248b908 which depends on numpy (1.18.5), version solving failed.

**Comment by frankligy** [comment]
Hi @TheWizier,

I didn't use poetry before, but let's just do a sanity check, if we go to pandas github, find the 1.3.4 release (https://github.com/pandas-dev/pandas/releases?page=3), download the zip and see the dependencies, it is clearly said:

```
# This file is auto-generated from environment.yml, do not modify.
# See that file for comments about the need/usage of each dependency.

numpy>=1.17.3
```
Also like I showed in this issue thread (https://github.com/frankligy/SNAF/issues/21#issuecomment-1912854494), I demonstrated a fresh conda, python3.7 on linux system should guarantee the successful installation. 

I guess I am just not sure where does `depends on pandas (1.3.4) which depends on numpy (>=1.19.2)` this come from, let me know if that makes sense.

Best,
Frnak
