### ISSUE TITLE
library lxml not supported. WikiPathways and LineageProfiler visualization will not work. Please install with pip install lxml.

### ISSUE THREAD

**Issue by renyuan001** [frankligy/SNAF#39]
docker run -v $PWD:/mnt frankligy123/altanalyze:0.7.0.1 DAS altanalyze_output groups.txt   # differential splicing
Current folder is /mnt
Identify differentailly spliced event, AltAnalyze output folder is /mnt/altanalyze_output, group file is /mnt/groups.txt
/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py:1320: UserWarning: findfont: Font family [u'sans-serif'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
library lxml not supported. WikiPathways and LineageProfiler visualization will not work. Please install with pip install lxml.
['--p', 'PSI', '--dPSI', '0', '--pval', '1', '--adjp', 'no', '--i', '/mnt/altanalyze_output/AltResults/AlternativeOutput/Hs_RNASeq_top_alt_junctions-PSI_EventAnnotation.txt', '--m', '/mnt/groups.txt']
Using a dPSI of: 0.0
Filtering on adjusted p-value: False
1
   Tumor     66
   Control     8
{1: [('Tumor', 'Control')]}
convertNonLogToLog: True
65 8 ('Tumor', 'Control')
36459 unique IDs compared (denominator).

This  step finished but some warning need pay attention. 
######
/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py:1320: UserWarning: findfont: Font family [u'sans-serif'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
library lxml not supported. WikiPathways and LineageProfiler visualization will not work. Please install with pip install lxml.
#######
We run the docker and the analysis at the same time,  how we can change the enviroment inside the docker.

**Comment by frankligy** [comment]
Hi @renyuan001,

Sorry for the confusion, there are many AltAnalyze container warning or even error information that can be safely ignored, you should have a plain text file with all the differentially spliced events in the `altanalyze_output/AlternativeOutput/Events-dPSI_0.0_rawp/PSI.high_vs_low.txt`, as long as the file is generated, this differential step is complete.

The warning and errors are some automatic execution for other downstream analysis, AltAnalyze itself is a one-stop toolkit for various transcriptome analysis (https://www.altanalyze.org/).

Best,
Frank

**Comment by renyuan001** [comment]
Thank you !
