### ISSUE TITLE
Neo-junction Annotation Clarification

### ISSUE THREAD

**Issue by yiolino** [frankligy/SNAF#51]
Hi, Thank you for the great software.

I have a question regarding the annotation format used for detected neo-junctions in SNAF’s output. Specifically, I would like clarification on the following:

1. In the expression "ENSG00000179912:E20.5-E27.1_57422959", could you explain what "1_57422959" represents?
2. In the expression "ENSG00000163635:U0.1_63864158-E4.2", what does the "U" indicate? I assume that "E" stands for exon and "I" stands for intron. Based on the following source code, it seems that "U" could represent UTR. Could you confirm if this is correct?

Reference:
https://github.com/nsalomonis/altanalyze/blob/64f77a77fb3c947bd5eaaaf759bfac2ab0a1b498/AltAnalyze.py#L371

Thank you for your assistance!

**Comment by frankligy** [comment]
Hi @yiolino,

First of all, AltAnalyze gene model collapsed multiple sources (ensembl, UCSC, etc) of annotated isoforms, which resulted in notation such as E20.5 and E27.1, which can be better illustrated in our supplemental figures and I also pasted here. Now for novel splicing site, we directly report them using the coordinate, so for `E27.1_57422959`, it means a novel splicing site at the location 57422959 falling into the annotated E27.1 region. 

Then for UTR, your interpretation is correct, U stands for UTR, and the trailing part is also the coordinate where the splicing starts.

![image](https://github.com/user-attachments/assets/f15209d5-026b-4d9b-829f-c80287cec9d9)

Best,
Frank

**Comment by yiolino** [comment]
Hi @frankligy,

Thank you for the detailed explanation! It makes sense now, and your clarification of collapsed gene model  notation and the coordinates for novel splicing sites was really helpful. 
Also, I’m glad to know that my interpretation of “U” as UTR was correct.

Thanks again for your prompt response!
